apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-lan2-conf
  namespace: {{ .Release.Name }}
spec:
  config: '{
      "cniVersion": "0.4.0",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "lanbr2",
          "isGateway": true,
          "isDefaultGateway": true,
          "master": "lo",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.2.0/24",
            "rangeStart": "192.168.2.2",
            "rangeEnd": "192.168.2.5",
            "gateway": "192.168.2.1"
          }
        },
        {
          "type": "firewall",
          "backend": "iptables"
        }
      ]
    }'
