apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-intrn-conf
  namespace: {{ .Release.Name }}
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens19",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "172.20.1.0/24",
        "rangeStart": "172.20.1.210",
        "rangeEnd": "172.20.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "172.20.1.1"
      }
    }'
