{- range $client, $params := .Values.annotationsNetwork }}
---
apiVersion: torchain.gate.way/v1alpha1
kind: TorChain
metadata:
  name: {{ include "tor-gateway.fullname" $ }}-{{ $client }}
  namespace: {{ $.Release.Name }}
  labels:
    {{- include "tor-gateway.labels" $ | nindent 4 }}
spec:
  drop: {{ .Values.description.sizeTorChain }}
  numberNode: {{ $params.numberNode }}
  inInterface: {{ $params.inInterface }}
  {{- if $params.ipGateWay }}
  ipGateWay: $params.ipGateWay
  {{- end }}
  outInterface: {{ $params.outInterface }}
  image: {{ $params.image }}
  vpnSecretNames: {{  $params.vpnSecretNames }}
  vpnSecretName: {{  $params.vpnSecretName }}
  {{- with .Values.nodeSelector }}
  nameK8sNode: {{ toYaml . | nindent 8 }}
  {{- end }}
{{- end }}

