---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.anupam.com
  resources:
  - helloapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.anupam.com
  resources:
  - helloapps/finalizers
  verbs:
  - update
- apiGroups:
  - apps.anupam.com
  resources:
  - helloapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps/v1
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps/v1
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - torchain.gate.way
  resources:
  - torchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - torchain.gate.way
  resources:
  - torchains/finalizers
  verbs:
  - update
- apiGroups:
  - torchain.gate.way
  resources:
  - torchains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
