# permissions for end users to edit torchains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: torchain-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tor-operator
    app.kubernetes.io/part-of: tor-operator
    app.kubernetes.io/managed-by: kustomize
  name: torchain-editor-role
rules:
- apiGroups:
  - torchain.gate.way
  resources:
  - torchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - torchain.gate.way
  resources:
  - torchains/status
  verbs:
  - get
