apiVersion: torchain.gate.way/v1alpha1
kind: TorChain
metadata:
  labels:
    app.kubernetes.io/name: torchain
    app.kubernetes.io/instance: torchain-sample
    app.kubernetes.io/part-of: tor-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tor-operator
  name: torchain-sample
  lengthchain:
spec:
  # TODO(user): Add fields here
  # metadata (init network interfaces)
  numbernode: 1 # 2, 3, ...
  typechainnode: open_vpn # or wireguard
  # environments
  gateway: ip_gateway # external ip gateway = 172.10.1.1
  config: config_file_name
  # volumeMounts
  tmpdir: tmp_directory
  configdir: configuration_directory
  # image
  image: image_vpn_client
  # nodeSelector
  namek8snode: host_name
  labelchain: my_chain_gateway
  lengthchain: 1

