apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: domain-city-server
  namespace: release
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: ns/number-node-chain/domain/city/server/wg

  # dest k8s secret
  destination:
    name: domain-city-server
    create: true

  # static secret refresh interval
  refreshAfter: 1h

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
