{{- range $client, $params := .Values.annotationsNetwork }}
---
apiVersion: v1    
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret-{{ $params.chain }}
  namespace: {{ $.Release.Name }}
type: Opaque
data:
  client.ovpn: {{ tpl ($.Files.Get $params.environments.pathToConfig) $ | b64enc }}
{{- end }}
