apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-client-deployment
  annotations:
    labelChain: "my_chain_gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain
  template:
    metadata:
      labels:
        app: chain
    spec:
      containers:
        - name:  demo-client
          image:  demo-client:latest
          imagePullPolicy: Never


