apiVersion: torchain.gate.way/v1alpha1
kind: TorChain
metadata:
  labels:
    app.kubernetes.io/name: torchain
    app.kubernetes.io/instance: torchain-sample
    app.kubernetes.io/part-of: tor-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tor-operator
  name: torchain-sample
spec:
  # TODO(user): Add fields here
  # metadata (init network interfaces)
  numberNode: 1 # 2, 3, ...
  ## typeNode: open_vpn # or wireguard
  ## nameTorChain: my_tor_gateway
  # environments
  vpnFileConfig: config_file_name
  # volumeMounts
  ## tmpDir: tmp_directory
  # interfaces
  inInterface: br-lan2-conf
  outInterface: br-extrn-conf
  ipGateWay: ip_gateway # external ip gateway = 172.10.1.1
  # vpnDirConfig: configuration_directory
  # image
  image: image_vpn_client
  # nodeSelector
  nameK8sNode: host_name
  # counter of switched to enother VPN Server
  switchServer: 0 

