apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    instance: torgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: torgateway
  template:
    metadata:
      labels:
        instance: torgateway
    spec:
      containers:
      - name: demo-client-pod
        image: demo-client
        imagePullPolicy: IfNotPresent
      - name: sidecar-container
        image: busybox
        livenessProbe:
          exec:
            command: ["wget", "-T2", "-O-", "ya.ru"]
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2

